version: "3.3"

networks:
  servcat-network:
    driver: bridge

services:
  servcat-api:
    container_name: servcat.api
    build:
      context: .
      dockerfile: docker/tomcat/Dockerfile
    image: servcat-api:1.0.0
    ports:
      - "8080:8080"
      - "8443:8443"
#    restart: on-failure
#    environment:
#        TZ: America/Sao_Paulo
    networks:
      - servcat-network
