-- 1 busca h2 tela servcat por grupo_classe
-- image: servcat-busca-h2-grup(FSG).png
  SELECT DISTINCT GRUPO
    FROM H2_GRUPO
   WHERE GRUPO LIKE '65%'
GROUP BY GRUPO --CLASSE --esta com erro o servcat pois o groupby esta escrito classe qnd deveria ser grupo
;

--2 resultado da busca no h2 do servcat
--imagem: servcat-aba-resultado-h2-GRUPO(FSG).png
SELECT C.CLASSE, G.GRUPO, C.N_NACIONAL NOME_DA_CLASSE, G.N_NACIONAL NOME_DO_GRUPO, C.NOTA_NACIONAL DESCRICAO_DA_CLASSE, G.NOTA_NACIONAL DESCRICAO_DO_GRUPO
FROM H2_CLASSE C, H2_GRUPO G
WHERE C.GRUPO = G.GRUPO
AND G.GRUPO = '65'
GROUP BY C.CLASSE, G.GRUPO, C.N_NACIONAL, G.N_NACIONAL, C.NOTA_NACIONAL, G.NOTA_NACIONAL
;

--3 exibicao de dados do h2 da busca da tela h2 do sercat
-- imagem: servcat-aba-CLASSE-ITEM_SUP-h2-grupo(FSG).png
SELECT C.CLASSE, G.GRUPO, C.N_NACIONAL NOME_DA_CLASSE, G.N_NACIONAL NOME_DO_GRUPO, C.NOTA_NACIONAL DESCRICAO_DA_CLASSE, G.NOTA_NACIONAL DESCRICAO_DO_GRUPO
FROM H2_CLASSE C, H2_GRUPO G
WHERE C.GRUPO = G.GRUPO
AND G.GRUPO = '65'
AND C.CLASSE = '6540'
;

--busca por nome:

SELECT DISTINCT N_NACIONAL FROM H2_GRUPO;

SELECT DISTINCT N_NACIONAL
FROM H2_GRUPO
WHERE N_NACIONAL LIKE 'EQUIPAMENTOS E%'
GROUP BY N_NACIONAL
;


SELECT C.CLASSE, G.GRUPO, C.N_NACIONAL NOME_DA_CLASSE, G.N_NACIONAL NOME_DO_GRUPO, C.NOTA_NACIONAL DESCRICAO_DA_CLASSE, G.NOTA_NACIONAL DESCRICAO_DO_GRUPO
FROM H2_CLASSE C, H2_GRUPO G
WHERE C.GRUPO = G.GRUPO
AND G.N_NACIONAL = 'EQUIPAMENTOS E ARTIGOS PARA USOS MÉDICO, DENTÁRIO E VETERINÁRIO'
GROUP BY C.CLASSE, G.GRUPO, C.N_NACIONAL, G.N_NACIONAL, C.NOTA_NACIONAL, G.NOTA_NACIONAL
;


SELECT C.CLASSE, G.GRUPO, C.N_NACIONAL NOME_DA_CLASSE, G.N_NACIONAL NOME_DO_GRUPO, C.NOTA_NACIONAL DESCRICAO_DA_CLASSE, G.NOTA_NACIONAL DESCRICAO_DO_GRUPO
FROM H2_CLASSE C, H2_GRUPO G
WHERE C.GRUPO = G.GRUPO
AND C.N_NACIONAL = 'DROGAS, PRODUTOS BIOLÓGICOS E REAGENTES'
GROUP BY C.CLASSE, G.GRUPO, C.N_NACIONAL, G.N_NACIONAL, C.NOTA_NACIONAL, G.NOTA_NACIONAL;