--busca h2 - servcat

--1 tela busca H2 - input FSC : 6505
SELECT DISTINCT CLASSE FROM H2_CLASSE;
-- variacao
SELECT * FROM H2_CLASSE;

--2 -- image: servcat-busca-h2-classe(FSC).png
SELECT DISTINCT CLASSE
FROM H2_CLASSE
WHERE CLASSE LIKE '6505%'
GROUP BY CLASSE;

-- imagem: servcat-aba-CLASSE-ITEM_SUP-h2-classe(FSC).png
SELECT C.CLASSE, G.GRUPO, C.N_NACIONAL NOME_DA_CLASSE, G.N_NACIONAL NOME_DO_GRUPO, C.NOTA_NACIONAL DESCRICAO_DA_CLASSE, G.NOTA_NACIONAL DESCRICAO_DO_GRUPO
FROM H2_CLASSE C, H2_GRUPO G
WHERE C.GRUPO = G.GRUPO
AND C.CLASSE = '6505'
GROUP BY C.CLASSE, G.GRUPO, C.N_NACIONAL, G.N_NACIONAL, C.NOTA_NACIONAL, G.NOTA_NACIONAL;

-- servcat-aba-CLASSE-ITEM_SUP-h2-classe(FSC).png
SELECT C.CLASSE, G.GRUPO, C.N_NACIONAL NOME_DA_CLASSE, G.N_NACIONAL NOME_DO_GRUPO, C.NOTA_NACIONAL DESCRICAO_DA_CLASSE, G.NOTA_NACIONAL DESCRICAO_DO_GRUPO
FROM H2_CLASSE C, H2_GRUPO G
WHERE C.GRUPO = G.GRUPO
AND G.GRUPO = '65' --:1
AND C.CLASSE = '6505' --:2
;