-- PASSO 1
SELECT /*+ FIRST_ROWS */ NIIN FROM GENERAL;
--VARIACAO
SELECT /*+ FIRST_ROWS */ NIIN FROM GENERAL;
-- 19.162.342
SELECT /*+ FIRST_ROWS */ count(*) FROM GENERAL;


---------
-- PASSO 2
SELECT  /*+ FIRST_ROWS */ NSN, COD_GEN 
  FROM GENERAL 
 WHERE ROWID IN ( SELECT  /*+ FIRST_ROWS */ GENERAL.ROWID
                   FROM GENERAL
                  WHERE GENERAL.NIIN = '014292368');
-- PASS 3 - SEG A
SELECT * FROM GENERAL WHERE COD_GEN = 14292368;

-- PASSO 4 - REFERENCIA
SELECT * FROM REFERENCE_NUMBER WHERE COD_GEN = 14292368;

-- PASS 5
SELECT S.CAGE_CODE
      ,S.CAGE_STATUS
      ,S.CAGE_TYPE
      ,S.CAGE_CAO
      ,S.CAGE_ADP
      ,S.CAGE_RPLM
      ,S.CAGE_ASSOC
      ,S.CAGE_AFFIL
      ,S.CAGE_SIZE
      ,S.CAGE_PRIMARY_BUSINESS
      ,S.CAGE_TYPE_OF_BUSINESS
      ,S.CAGE_WOMAN_OWNED
      ,S.CAGE_SIC_CODES
      ,S.CAGE_FAX
      ,SUBSTR(S.CAGE_COMPANY_NAME, 1, 255) CAGE_COMPANY_NAME
      ,SUBSTR(S.CAGE_COMPANY_ADDRESS, 1, 255) CAGE_COMPANY_ADDRESS
      ,S.CAGE_PO_BOX
      ,S.CAGE_CITY
      ,S.CAGE_STATE
      ,S.CAGE_COUNTRY
      ,S.CAGE_ZIP_CODE
      ,S.CAGE_TELEPHONE
      ,S.CAGE_FORMER_ADDRESS
FROM SUPPLIER S
WHERE CAGE_CODE = '81349';
---

-- GERENCIA
SELECT *
  FROM MANAGEMENT
 WHERE COD_GEN = 14292368;

SELECT * FROM CHARACTERISTICS WHERE COD_GEN = 14292368;


